var irregularA = {
  'ar' : {
    'abuhar'      : ['abúh'],
    'actuar'      : ['actú'],
    'acertar'     : ['aciert'],
    'adecuar'     : ['adecu'],
    'adeudar'     : ['adeud'],
    'ahijar'      : ['ahíj'],
    'ahumar'      : ['ahú'],
    'aislar'      : ['aísl'],
    'andar'       : ['anduv'],
    'aunar'       : ['aún'],
    'autoinflar'  : ['autoínfl'],
    'averiguar'   : ['averigü'],
    'cazar'       : ['cac'],
    'colgar'      : ['cuelg', 'colgu', 'cuelgu'],
    'contar'      : ['cuent'],
    'comenzar'    : ['comienz', 'comenc', 'comienc'],
    'dar'         : ['d','di'],
    'degollar'    : ['degüell'],
    'descafeinar' : ['descafeín'],
    'desosar'     : ['deshues'],
    'enviar'      : ['enví'],
    'errar'       : ['yerr'],
    'estar'       : ['estuv'],
    'forzar'      : ['fuerz','fuerc'],
    'jugar'       : ['jueg', 'juegu', 'jugu'],
    'pagar'       : ['pagu'],
    'regar'       : ['rieg', 'riegu', 'regu'],
    'rehilar'     : ['rehíl'],
    'rehusar'     : ['rehús'],
    'sacar'       : ['saqu'],
    'volcar'      : ['vuelc', 'volqu', 'vuelqu']
  },

  'er' : {
    'agradecer'   : ['agradezc'],
    'caber'       : ['quep','cup'],
    'caer'        : ['caig', 'caí', 'cay'],
    'cocer'       : ['cuez', 'cuec', 'coz'],
    'entender'    : ['entiend'],
    'fosforescer' : ['fosforezc'],
    'mover'       : ['muev'],
    'oler'        : ['huel'],
    'placer'      : ['plazc', 'plugu'],
    'poder'       : ['pued', 'podr', 'pud'],
    'poner'       : ['pong', 'pus', 'puest'],
    'proteger'    : ['protej'],
    'querer'      : ['quier', 'querr', 'quis'],
    'raer'        : ['raig', 'ray']
    'roer'        : {},
    'saber'       : {},
    'ser'         : {},
    'tañer'       : {},
    'tener'       : {},
    'traer'       : {},
    'valer'       : {},
    'ver'         : {},
    'yacer'       : {}
  },

  'ir' : {
    'adquirir'    : ['adquier'],
    'argüir'      : ['arguy'],
    'asir'        : ['asg'],
    'bendecir'    : ['bendig', 'bendic','bendij'],
    'ceñir'       : ['ciñ'],
    'conducir'    : ['conduzc', 'conduj'],
    'construir'   : ['construy'],
    'contradecir' : ['contradig','contradij','contradir','contradic'],
    'counir'      : ['coún'],
    'decir'       : ['dig','dij','dir'],
    'delinquir'   : ['delinc'],
    'discernir'   : ['disciern'],
    'dirigir'     : ['dirij'],
    'distinguir'  : ['disting']
    'dormir'      : ['duerm', 'durm'],
    'elegir'      : ['elij','elig'],
    'erguir'      : ['irg','yerg','iergu','yergu'],
    'esparcir'    : ['esparz']
    'ir'          : ['vay','fuer','fues'],
    'jugar'       : {},
    'lucir'       : ['luzc'],
    'mullir'      : {},
    'oír'         : {},
    'pedir'       : {},
    'pudrir'      : {},
    'podrir'      : {},
    'salir'       : {},
    'sentir'      : {},
    'sonreír'     : {},
    'venir'       : {}
  }



  }
}
