var irregular = {
  'ar' : {
    'acertar'     : ['aciert'],
    'adquirir'    : ['adquier'],
    'agradecer'   : ['agradezc'],
    'andar'       : ['anduv'],
    'argüir'      : ['arguy'],
    'asir'        : ['asg'],
    'bendecir'    : ['bendig', 'bendic','bendij'],
    'caber'       : ['quep','cup'],
    'cazar'       : ['cac'],
    'caer'        : ['caig', 'caí', 'cay'],
    'ceñir'       : ['ciñ'],
    'colgar'      : ['cuelg', 'colgu', 'cuelgu'],
    'conducir'    : ['conduzc', 'conduj'],
    'construir'   : ['construy'],
    'contar'      : ['cuent'],
    'contradecir' : ['contradig','contradij','contradir','contradic'],
    'comenzar'    : ['comienz', 'comenc', 'comienc']
    'counir'      : ['coún'],
    'dar'         : ['d','di'],
    'decir'       : ['dig','dij','dir'],
    'delinquir'   : ['delinc'],
    'desosar'     : ['deshues'],
    'discernir'   : ['disciern'],
    'dirigir'     : ['dirij'],
    'distinguir'  : ['disting']
    'dormir'      : ['duerm', 'durm'],
    'elegir'      : ['elij','elig'],
    'entender'    : ['entiend']
    'erguir'      : ['irg','yerg','iergu','yergu'],
    'errar'       : ['yerr'],
    'esparcir'    : ['esparz']
    'estar'       : ['estuv'],
    'forzar'      : ['fuerz','fuerc']
    'haber'       : {},
    'hacer'       : {},
    'ir'          : ['vay','fuer','fues'],
    'jugar'       : {},
    'leer'        : {},
    'lucir'       : ['luzc'],
    'mover'       : {},
    'mullir'      : {},
    'oír'         : {},
    'oler'        : {},
    'pedir'       : {},
    'poder'       : {},
    'poner'       : {},
    'pudrir'      : {},
    'podrir'      : {},
    'querer'      : {},
    'roer'        : {},
    'saber'       : {},
    'salir'       : {},
    'sentir'      : {},
    'ser'         : {},
    'sonreír'     : {},
    'tañer'       : {},
    'tener'       : {},
    'traer'       : {},
    'valer'       : {},
    'venir'       : {},
    'ver'         : {},
    'yacer'       : {}
  }
}
